import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import type { WorkspaceSnapshot, UserGoalPacket, HandoffContract } from '../../shared/types';
import type { ModelRouter } from '../routing/ModelRouter';
import type { ModelIndexer } from '../routing/ModelIndexer';
import type { RoleSelector } from '../core/RoleSelector';
import type { ClarifierAgent } from '../agents/ClarifierAgent';

export interface IntakeDeps {
  workspaceRoot: string;
  clarifier: ClarifierAgent;
  roleSelector: RoleSelector;
  modelIndexer?: ModelIndexer;
  router?: ModelRouter;
  apiKeys: Record<string, string>;
}

export interface IntakeResult {
  taskId: string;
  workspace: WorkspaceSnapshot;
  goalPacket: UserGoalPacket;
  projectDocs: { agentsMd?: string; omniMd?: string };
  tier: 'LOW' | 'MEDIUM' | 'HIGH';
  phases: string[];
  useSelfPrompting: boolean;
}

export function parseJsonSafe(text: string): any {
  if (!text) return null;
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const raw = fenced ? fenced[1] : text;
  try { return JSON.parse(raw.trim()); } catch { return null; }
}

export async function scanWorkspace(workspaceRoot: string): Promise<WorkspaceSnapshot> {
  const files: string[] = [];
  try {
    const entries = fs.readdirSync(workspaceRoot, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        files.push(entry.name + '/');
      } else {
        files.push(entry.name);
      }
    }
  } catch {
    // Empty workspace or permission error
  }

  const hasPackageJson = fs.existsSync(path.join(workspaceRoot, 'package.json'));
  const hasReadme = fs.existsSync(path.join(workspaceRoot, 'README.md'));
  const techStack: string[] = [];
  if (hasPackageJson) {
    try {
      const pkg = JSON.parse(fs.readFileSync(path.join(workspaceRoot, 'package.json'), 'utf-8'));
      if (pkg.dependencies) techStack.push(...Object.keys(pkg.dependencies));
      if (pkg.devDependencies) techStack.push(...Object.keys(pkg.devDependencies));
    } catch {
      // Ignore parse errors
    }
  }

  return { fileTree: files, hasPackageJson, hasReadme, techStack };
}

export async function refreshModelIndex(
  modelIndexer: ModelIndexer | undefined,
  router: ModelRouter | undefined,
  apiKeys: Record<string, string>
): Promise<void> {
  if (!modelIndexer || !router) return;
  try {
    (modelIndexer as any).apiKeys = apiKeys;
    await modelIndexer.refreshIndex();
    router.syncModels(modelIndexer.getModels());
  } catch (e) {
    // Model index refresh is non-critical
  }
}

export async function draftProjectDocs(
  goal: string,
  router: ModelRouter | undefined,
  apiKeys: Record<string, string>
): Promise<{ agentsMd: string; omniMd: string }> {
  if (!router) {
    return {
      agentsMd: `# AGENTS.md\n\n# Conventions\n- Language: TypeScript\n- Style: clear, typed, minimal\n\n# Goal\n${goal}\n`,
      omniMd: `# OMNI.md\n\n# Project\n${goal}\n\n# Memory\n- Generated by Omni bootstrap.\n`,
    };
  }

  try {
    const res = await router.call(
      { phase: 'intake', agentRole: 'clarifier', complexity: 'low' },
      `Generate two markdown docs for a new project.\nGOAL: ${goal}\n\nReturn ONLY JSON: {"agentsMd": string, "omniMd": string}.\n- agentsMd: project conventions, coding style, testing, how to run.\n- omniMd: project overview, goal, key decisions, memory for future sessions.`,
      'You are a project bootstrapper. Return ONLY JSON.',
      apiKeys
    );
    const parsed = parseJsonSafe(res.content || '');
    return {
      agentsMd: parsed?.agentsMd || `# AGENTS.md\n\n# Conventions\n- Language: TypeScript\n- Style: clear, typed, minimal\n- Tests: include where practical\n\n# Goal\n${goal}\n`,
      omniMd: parsed?.omniMd || `# OMNI.md\n\n# Project\n${goal}\n\n# Memory\n- Generated by Omni bootstrap.\n`,
    };
  } catch {
    return {
      agentsMd: `# AGENTS.md\n\n# Conventions\n- Language: TypeScript\n- Style: clear, typed, minimal\n\n# Goal\n${goal}\n`,
      omniMd: `# OMNI.md\n\n# Project\n${goal}\n\n# Memory\n- Generated by Omni bootstrap.\n`,
    };
  }
}

export function readProjectDocs(workspaceRoot: string): { agentsMd?: string; omniMd?: string } {
  const docs: { agentsMd?: string; omniMd?: string } = {};
  try {
    const a = path.join(workspaceRoot, 'AGENTS.md');
    const o = path.join(workspaceRoot, 'OMNI.md');
    if (fs.existsSync(a)) docs.agentsMd = fs.readFileSync(a, 'utf-8');
    if (fs.existsSync(o)) docs.omniMd = fs.readFileSync(o, 'utf-8');
  } catch { /* ignore */ }
  return docs;
}

export function isCleanProject(workspace: WorkspaceSnapshot): boolean {
  const meaningful = (workspace.fileTree || []).filter((f) =>
    !/^(node_modules|\.git|\.vscode|\.omniflow|dist|out|build|coverage)$/.test(f) &&
    !f.startsWith('.') &&
    !/\.(png|jpg|jpeg|gif|ico|lock|log)$/i.test(f)
  );
  return meaningful.length === 0;
}

export async function runIntake(
  rawGoal: string,
  deps: IntakeDeps
): Promise<IntakeResult> {
  const taskId = `task_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`;

  // Scan workspace
  const workspace = await scanWorkspace(deps.workspaceRoot);

  // Refresh model index (non-critical)
  await refreshModelIndex(deps.modelIndexer, deps.router, deps.apiKeys);

  // Bootstrap project docs if needed (deferred to phase with approval)
  const projectDocs = readProjectDocs(deps.workspaceRoot);

  // Create goal packet via clarifier
  const intakeContract: HandoffContract = {
    subtaskId: `intake_${taskId}`,
    agentRole: 'clarifier',
    successCriteria: ['Goal packet created'],
    artifactTargets: [{ filePath: `.omniflow/tasks/${taskId}/goal-packet.json`, contentType: 'config' }],
    contextPacket: { taskId, goal: rawGoal, workspaceSnapshot: workspace },
  };

  const goalManifest = await deps.clarifier.execute(intakeContract, deps.workspaceRoot);
  const goalPacket: UserGoalPacket = JSON.parse(goalManifest.artifacts[0].content);

  // Triage via RoleSelector
  const selection = deps.roleSelector.select(goalPacket.goal, goalPacket.complexity);

  return {
    taskId,
    workspace,
    goalPacket,
    projectDocs,
    tier: selection.tier,
    phases: selection.phases,
    useSelfPrompting: selection.useSelfPrompting,
  };
}
